---
- name: Azure AD Automation using Ansible
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    # Azure AD Application Registration Variables
    client_id: "195e8969-c853-47b4-83d0-36e044d83923"    
    client_secret: "{{ lookup('env', 'AZURE_CLIENT_SECRET') }}"  
    tenant_id: "e2e46ae3-2dee-4eed-a074-ddffd760ab2b"  
    graph_api_url: "https://graph.microsoft.com/v1.0"  
    user_email: "Jayanta.Banerjee@amitomar63gmail.onmicrosoft.com"  
    group_id: "361a2177-941b-4d63-8283-d59d58ad7fc0"   

  tasks:

    - name: Get Access Token from Azure AD
      uri:
        url: "https://login.microsoftonline.com/{{ tenant_id }}/oauth2/v2.0/token"
        method: POST
        headers:
          Content-Type: "application/x-www-form-urlencoded"
        body:
          client_id: "{{ client_id }}"
          client_secret: "{{ client_secret }}"
          scope: "https://graph.microsoft.com/.default"
          grant_type: "client_credentials"
        body_format: form-urlencoded
        return_content: yes
      register: token_response
      failed_when: token_response.status != 200
      retries: 3
      delay: 10

    - name: Debug - Show Access Token Response
      debug:
        msg: "Access Token Retrieved Successfully!"
      when: token_response.status == 200

    - name: Set access token fact
      set_fact:
        access_token: "{{ token_response.json.access_token }}"

    - name: Check for User in Azure AD
      uri:
        url: "{{ graph_api_url }}/users/{{ user_email }}"
        method: GET
        headers:
          Authorization: "Bearer {{ access_token }}"
          Content-Type: "application/json"
      register: user_check
      failed_when: user_check.status not in [200, 404]

    - name: Debug - Show User Check Response
      debug:
        var: user_check.json
      when: user_check.status == 200

    - name: Change Group Assignment for User
      uri:
        url: "{{ graph_api_url }}/groups/{{ group_id }}/members/$ref"
        method: POST
        headers:
          Authorization: "Bearer {{ access_token }}"
          Content-Type: "application/json"
        body:
          "@odata.id": "{{ graph_api_url }}/directoryObjects/{{ user_check.json.id }}"
        status_code: [204, 400]
      when: user_check.status == 200

    - name: Disable User Account
      uri:
        url: "{{ graph_api_url }}/users/{{ user_email }}"
        method: PATCH
        headers:
          Authorization: "Bearer {{ access_token }}"
          Content-Type: "application/json"
        body_format: json
        body:
          accountEnabled: false
        status_code: [200, 204]
      when: user_check.status == 200

    - name: Enable User Account
      uri:
        url: "{{ graph_api_url }}/users/{{ user_email }}"
        method: PATCH
        headers:
          Authorization: "Bearer {{ access_token }}"
          Content-Type: "application/json"
        body_format: json
        body:
          accountEnabled: true
        status_code: [200, 204]
      when: user_check.status == 200

    - name: Create User Account if not exist
      uri:
        url: "{{ graph_api_url }}/users"
        method: POST
        headers:
          Authorization: "Bearer {{ access_token }}"
          Content-Type: "application/json"
        body_format: json
        body:
          accountEnabled: true
          displayName: "New User"
          mailNickname: "newuser"
          userPrincipalName: "newuser@yourdomain.com"
          passwordProfile:
            forceChangePasswordNextSignIn: true
            password: "P@ssw0rd!"
        status_code: 201
      when: user_check.status == 404

    - name: Debug - Show User Creation Response
      debug:
        msg: "New user account successfully created!"
      when: user_check.status == 404
