---
- name: Check if a user exists in Azure AD (AZX Compatible)
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Get Access Token from Azure AD
      uri:
        url: "https://login.microsoftonline.com/{{ lookup('env', 'AZURE_TENANT_ID') }}/oauth2/v2.0/token"
        method: POST
        headers:
          Content-Type: "application/x-www-form-urlencoded"
        body:
          client_id: "{{ lookup('env', 'AZURE_CLIENT_ID') }}"
          client_secret: "{{ lookup('env', 'AZURE_CLIENT_SECRET') }}"
          scope: "https://graph.microsoft.com/.default"
          grant_type: "client_credentials"
        body_format: form-urlencoded
        return_content: yes
      register: token_response
      failed_when: token_response.status != 200

    - name: Extract Access Token
      set_fact:
        access_token: "{{ token_response.json.access_token }}"

    - name: Check if user exists in Azure AD
      uri:
        url: "https://graph.microsoft.com/v1.0/users/user@example.com"
        method: GET
        headers:
          Authorization: "Bearer {{ access_token }}"
          Content-Type: "application/json"
      register: user_info
      failed_when: user_info.status not in [200, 404]

    - name: Debug - Display User Info
      debug:
        var: user_info.json
