---
- name: Azure AD User Management
  hosts: localhost
  tasks:
  
    - name: Check if a user exists
      azure.azcollection.azure_rm_aduser_info:
        user_principal_name: "testuser@yourdomain.com"

    - name: Create a new user
      azure.azcollection.azure_rm_aduser:
        user_principal_name: "newuser@yourdomain.com"
        display_name: "New User"
        password: "SecurePass123!"
        account_enabled: yes

    - name: Disable a user account
      azure.azcollection.azure_rm_aduser:
        user_principal_name: "user-to-disable@yourdomain.com"
        account_enabled: no

    - name: Enable a user account
      azure.azcollection.azure_rm_aduser:
        user_principal_name: "user-to-enable@yourdomain.com"
        account_enabled: yes
