---
- name: Azure AD Automation using Ansible
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    graph_api_url: "https://graph.microsoft.com/v1.0"
    enable_account: "{{ tf | bool }}"
    exmp: "{{ user_id }}"
    tenant_id: "195e8969-c853-47b4-83d0-36e044d83923"
    client_id: "e2e46ae3-2dee-4eed-a074-ddffd760ab2b"
    client_secret: "PQZ8Q~XSmMsU4dbgk2KyWMHK1h8X7ciD~H.1_csi"
    INCIDENT_NUMBER: "{{ INCIDENT_NUMBER }}"
    service_now_instance: "{{ service_now_instance }}"
    service_now_username: "{{ service_now_username }}"
    service_now_password: "{{ service_now_password }}"

    # ServiceNow ticket info
    ticket_type: "incident"  # or "request"
    short_description: "Updated Ticket Description"
    description: "Updated ticket details."
    priority: "3"
    impact: "2"
    urgency: "2"
    state: "2"
    assigned_to: "admin"
    assignment_group: "IT Support"
    comments: "Ticket is being worked on."
    work_notes: "Engineer started troubleshooting."
    request_state: "approved"
    stage: "fulfilling"
    approval: "approved"
    category: "network"
    service_offering: "IT Helpdesk"
    contact_type: "email"

  tasks:
    - name: Get Access Token
      uri:
        url: "https://login.microsoftonline.com/{{ tenant_id }}/oauth2/v2.0/token"
        method: POST
        headers:
          Content-Type: "application/x-www-form-urlencoded"
        body:
          client_id: "{{ client_id }}"
          client_secret: "{{ client_secret }}"
          scope: "https://graph.microsoft.com/.default"
          grant_type: "client_credentials"
        body_format: form-urlencoded
        return_content: yes
      register: token_response
      failed_when: token_response.status != 200

    - name: Set access token fact
      set_fact:
        access_token: "{{ token_response.json.access_token }}"

    - name: Debug - Show Access Token Status
      debug:
        msg: "Access Token Retrieval: {{ 'Successful' if token_response.status == 200 else 'Unsuccessful' }}"

    - name: Verify target user exists
      uri:
        url: "{{ graph_api_url }}/users/{{ exmp }}"
        method: GET
        headers:
          Authorization: "Bearer {{ access_token }}"
          Content-Type: "application/json"
      register: user_verify
      failed_when: false

    - name: Debug - Show user verify result
      debug:
        var: user_verify

    - name: Enable or Disable User Account
      uri:
        url: "{{ graph_api_url }}/users/{{ exmp }}"
        method: PATCH
        headers:
          Authorization: "Bearer {{ access_token }}"
          Content-Type: "application/json"
        body:
          accountEnabled: "{{ enable_account | lower }}"
        body_format: json
      register: account_update
      failed_when: false

    - name: Debug - Show account update response
      debug:
        var: account_update

    # --- ServiceNow Section ---

    - name: Determine table based on ticket_type
      set_fact:
        table_name: "{{ 'incident' if ticket_type == 'incident' else 'sc_request' }}"

    - name: Search for ticket using short_description
      uri:
        url: "https://{{ service_now_instance }}/api/now/table/{{ table_name }}?sysparm_query=short_description={{ short_description | urlencode }}&sysparm_limit=1"
        method: GET
        user: "{{ service_now_username }}"
        password: "{{ service_now_password }}"
        force_basic_auth: yes
        headers:
          Content-Type: "application/json"
        return_content: yes
      register: incident_search
      failed_when: incident_search.status not in [200]

    - name: Debug - Search results
      debug:
        var: incident_search.json.result

    - name: Set sys_id from search result
      set_fact:
        requested_sys_id: "{{ incident_search.json.result[0].sys_id }}"
      when: incident_search.json.result | length > 0

    - name: Prepare request body for update
      set_fact:
        request_body: >-
          {%- if ticket_type == 'incident' -%}
          {
            "short_description": "{{ short_description }}",
            "description": "{{ description }}",
            "impact": "{{ impact }}",
            "urgency": "{{ urgency }}",
            "priority": "{{ priority }}",
            "comments": "{{ comments }}",
            "work_notes": "{{ work_notes }}",
            "state": "{{ state }}"
          }
          {%- else -%}
          {
            "short_description": "{{ short_description }}",
            "description": "{{ description }}",
            "priority": "{{ priority }}",
            "assigned_to": "{{ assigned_to }}",
            "assignment_group": "{{ assignment_group }}",
            "comments": "{{ comments }}",
            "work_notes": "{{ work_notes }}",
            "request_state": "{{ request_state }}",
            "stage": "{{ stage }}",
            "approval": "{{ approval }}",
            "category": "{{ category }}",
            "service_offering": "{{ service_offering }}",
            "contact_type": "{{ contact_type }}"
          }
          {%- endif -%}

    - name: Update Incident or Request in ServiceNow
      uri:
        url: "https://{{ service_now_instance }}/api/now/table/{{ table_name }}/{{ requested_sys_id }}"
        method: PATCH
        user: "{{ service_now_username }}"
        password: "{{ service_now_password }}"
        force_basic_auth: yes
        headers:
          Content-Type: "application/json"
        body_format: json
        body: "{{ request_body }}"
        status_code: [200, 204]
      when: requested_sys_id is defined
      register: response

    - name: Show Updated Ticket Details
      debug:
        msg: "{{ response.json if response.json is defined else 'Update Successful (No body returned)' }}"
